project:
  type: website
  output-dir: docs

website:
  title: "My Engineering Journey Cambodia"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - text: Videos
        href: videos.qmd
      - text: About Us
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/my-engineering-journey-cambodia
  page-footer:
    left: "My Engineering Journey Cambodia"
    right: "Inspiring Future Engineers"

format:
  html:
    theme: cosmo
    anchor-sections: false
    toc: false
    smooth-scroll: true
    css: styles.css
    include-in-header: head.html
    include-after-body: scripts.html

editor: source
